package generator

import (
	"fmt"
	"os"
	"strings"
	"time"

	"github.com/Ghostalex07/PolkitGuard/internal/models"
)

type Generator struct {
	author      string
	version     string
	description string
}

func NewGenerator() *Generator {
	return &Generator{
		author:      "admin",
		version:     "1.0.0",
		description: "",
	}
}

func (g *Generator) SetAuthor(author string) *Generator {
	g.author = author
	return g
}

func (g *Generator) SetVersion(version string) *Generator {
	g.version = version
	return g
}

func (g *Generator) SetDescription(desc string) *Generator {
	g.description = desc
	return g
}

func (g *Generator) GenerateFromFindings(findings []models.Finding, outputPath string) error {
	rules := g.convertFindingsToRules(findings)
	content := g.generateRulesContent(rules)

	if outputPath == "" {
		fmt.Print(content)
		return nil
	}

	return os.WriteFile(outputPath, []byte(content), 0644)
}

func (g *Generator) GenerateSecureRules(actions []string, identity string, result string) string {
	var sb strings.Builder

	sb.WriteString(fmt.Sprintf("/*\n"))
	sb.WriteString(fmt.Sprintf(" * Polkit Security Rules\n"))
	sb.WriteString(fmt.Sprintf(" * Generated: %s\n", time.Now().Format(time.RFC822)))
	sb.WriteString(fmt.Sprintf(" * Author: %s\n", g.author))
	sb.WriteString(fmt.Sprintf(" * Version: %s\n", g.version))
	sb.WriteString(fmt.Sprintf(" */\n\n"))

	for _, action := range actions {
		_ = action
		sb.WriteString(fmt.Sprintf("[%s]\n", identity))
		sb.WriteString(fmt.Sprintf("ResultAny=%s\n", result))
		sb.WriteString(fmt.Sprintf("ResultActive=%s\n", result))
		sb.WriteString(fmt.Sprintf("ResultInactive=auth_admin_keep\n\n"))
	}

	return sb.String()
}

func (g *Generator) GenerateTemplate(templateType string) string {
	switch templateType {
	case "admin":
		return g.generateAdminTemplate()
	case "service":
		return g.generateServiceTemplate()
	case "network":
		return g.generateNetworkTemplate()
	case "user":
		return g.generateUserTemplate()
	default:
		return g.generateDefaultTemplate()
	}
}

func (g *Generator) generateAdminTemplate() string {
	return `/* Polkit Admin Template */
/* Restrict admin actions to wheel group only */

[unix-group:wheel]
ResultAny=auth_admin_keep
ResultActive=auth_admin_keep
ResultInactive=auth_admin_keep

[unix-user:root]
ResultAny=auth_admin
`
}

func (g *Generator) generateServiceTemplate() string {
	return `/* Polkit Service Template */
/* Control systemd service management */

[unix-group:wheel]
ResultAny=auth_admin_keep
ResultActive=auth_admin_keep
ResultInactive=auth_admin_keep

[unix-user:systemd-network]
ResultAny=no
`
}

func (g *Generator) generateNetworkTemplate() string {
	return `/* Polkit Network Template */
/* Restrict network configuration */

[unix-group:netadmin]
ResultAny=auth_admin
ResultActive=auth_admin
ResultInactive=auth_admin

[unix-user:*]
ResultAny=no
`
}

func (g *Generator) generateUserTemplate() string {
	return `/* Polkit User Management Template */
/* Control user account modifications */

[unix-group:wheel]
ResultAny=auth_admin_keep
ResultActive=auth_admin_keep
ResultInactive=auth_admin_keep

[unix-user:root]
ResultAny=auth_admin
`
}

func (g *Generator) generateDefaultTemplate() string {
	return `/* Polkit Security Rules */
/* Generated by PolkitGuard */

[unix-group:wheel]
ResultAny=auth_admin_keep
ResultActive=auth_admin_keep
ResultInactive=auth_admin_keep
`
}

func (g *Generator) convertFindingsToRules(findings []models.Finding) []models.PolkitRule {
	var rules []models.PolkitRule

	for _, f := range findings {
		if f.Rule != nil {
			rule := models.PolkitRule{
				Action:    f.Rule.Action,
				Identity:  f.Rule.Identity,
				ResultAny: g.suggestSecureResult(f),
			}
			rules = append(rules, rule)
		}
	}

	return rules
}

func (g *Generator) suggestSecureResult(finding models.Finding) string {
	if finding.Rule == nil {
		return "auth_admin"
	}

	switch finding.Severity {
	case models.SeverityCritical:
		return "auth_admin_keep"
	case models.SeverityHigh:
		return "auth_admin"
	case models.SeverityMedium:
		return "auth_self_keep"
	case models.SeverityLow:
		return "auth_self"
	default:
		return "auth_admin"
	}
}

func (g *Generator) generateRulesContent(rules []models.PolkitRule) string {
	var sb strings.Builder

	sb.WriteString(fmt.Sprintf("/*\n"))
	sb.WriteString(fmt.Sprintf(" * Secure Polkit Rules\n"))
	sb.WriteString(fmt.Sprintf(" * Generated by PolkitGuard: %s\n", time.Now().Format(time.RFC822)))
	sb.WriteString(fmt.Sprintf(" * Author: %s\n", g.author))
	sb.WriteString(fmt.Sprintf(" */\n\n"))

	for _, rule := range rules {
		sb.WriteString(fmt.Sprintf("[%s]\n", rule.Identity))
		sb.WriteString(fmt.Sprintf("ResultAny=%s\n", rule.ResultAny))
		if rule.ResultActive != "" {
			sb.WriteString(fmt.Sprintf("ResultActive=%s\n", rule.ResultActive))
		}
		if rule.ResultInactive != "" {
			sb.WriteString(fmt.Sprintf("ResultInactive=%s\n", rule.ResultInactive))
		}
		sb.WriteString("\n")
	}

	return sb.String()
}

func (g *Generator) GenerateConfig() string {
	return `{
  "polkit_version": "1.18.0",
  "generated": "` + time.Now().Format(time.RFC3339) + `",
  "author": "` + g.author + `",
  "rules": {
    "admin": {
      "identity": "unix-group:wheel",
      "result": "auth_admin_keep",
      "description": "Admin group access"
    },
    "service": {
      "identity": "unix-user:systemd-network",
      "result": "no",
      "description": "Service account restrictions"
    },
    "network": {
      "identity": "unix-group:netadmin",
      "result": "auth_admin",
      "description": "Network admin access"
    }
  }
}
`
}